version: '3.3'
services:
  jenkins:
    image: h1kkan/jenkins-docker:lts
    privileged: true
    user: root 
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      #- /root/.docker/config.json:/root/.docker/config.json
      - ~/.ssh:/root/.ssh:ro
      - ./jenkins:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      - /var/db:/var/db:Z
      # - /usr/local/bin/dockerize:/usr/bin/dockerize
      # - /usr/local/bin/docker:/usr/local/bin/docker